server:
  port: 8080
  
  
zuul:
  routes:
    oauth:
      path: /oauth/**
      url: http://localhost:8081/spring-security-oauth-server/oauth
    spring-security-oauth-resource:
      path: /spring-security-oauth-resource/**
      url: http://localhost:8082/spring-security-oauth-resource
  sensitive-headers: Cookie,Set-Cookie
  
  
security:
  oauth2:
    resource:
      jwt:
        key-value: 123